<a href="https://colab.research.google.com/github/Shrutika01234/WindPowerForcasting/blob/master/WindPower.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uplodade = files.upload()

Saving train.csv to train.csv


In [ ]:
import pandas as pd 
train_data = pd.read_csv('train.csv')

In [ ]:
train_data.head()

tracking_id             datetime  wind_speed  atmospheric_temperature  \
0  datetimeWM_33725  2019-08-04 14:33:20   94.820023               -99.000000   
1            WM_698  2018-11-05 10:13:20  241.832734                27.764785   
2          WM_39146  2019-09-14 14:03:20   95.484724                      NaN   
3           WM_6757  2018-12-25 15:33:20  238.819424               -99.000000   
4          WM_21521  2019-05-04 03:13:20   10.722890                      NaN   

   shaft_temperature  blades_angle  gearbox_temperature  engine_temperature  \
0          41.723019     -0.903423            82.410573           42.523015   
1         -99.000000    -99.000000            44.104919           46.258870   
2          41.855473     12.652763            42.322098           42.878552   
3          45.443914     15.115323            44.759643           47.282101   
4          41.981183      1.715696           -17.616459           43.469852   

   motor_torque  generator_temperature  ...  windmill_body_temperature  \
0   2563.124522              76.665560  ...                        NaN   
1   2372.384119              78.129803  ...                        NaN   
2   1657.169646              67.654469  ...                  45.033197   
3   2888.134079              95.389974  ...                  44.827154   
4    781.695419              37.423065  ...                 -99.000000   

   wind_direction   resistance  rotor_torque  turbine_status  cloud_level  \
0      239.836388  2730.310605     42.084666              BA       Medium   
1      337.944723  1780.207200    107.888643              A2       Medium   
2      227.850294  1666.049900    -42.931459             ABC       Medium   
3      492.081520  1964.502895     42.744596             ABC          NaN   
4      259.274601  1177.516152     13.387289             AAA       Medium   

  blade_length blade_breadth  windmill_height  windmill_generated_power  
0     2.217542      0.314065        24.281689                  6.766521  
1     4.210346      0.448494        27.262139                  5.966275  
2     2.719475      0.302321        27.366127                  2.874342  
3     4.857385      0.367140        24.287767                 14.851089  
4          NaN      0.453374        27.971650                  3.519074  

[5 rows x 22 columns]

In [ ]:
train_data.drop('tracking_id',inplace=True,axis=1)
train_data.drop('datetime',inplace=True,axis=1)


train_data = train_data.dropna(axis=0,how='any')

train_data['cloud_level'].replace(['Medium','Low','Extremely Low'],[0,1,2],inplace=True)
train_data['turbine_status'].replace(['ABC','AAA','BD','AC','BB','BCB','BA','A2','AB','BBB','A','B','D','B2'],[0,1,2,3,4,5,6,7,8,9,10,11,12,13],inplace=True)


from sklearn.preprocessing import MinMaxScaler 
sc = MinMaxScaler()

train_data[['wind_speed','atmospheric_temperature','shaft_temperature','blades_angle','gearbox_temperature','engine_temperature','motor_torque','generator_temperature','atmospheric_pressure','area_temperature','windmill_body_temperature','wind_direction','resistance','rotor_torque','turbine_status','cloud_level','blade_length','blade_breadth','windmill_height']] = sc.fit_transform(train_data[['wind_speed','atmospheric_temperature','shaft_temperature','blades_angle','gearbox_temperature','engine_temperature','motor_torque','generator_temperature','atmospheric_pressure','area_temperature','windmill_body_temperature','wind_direction','resistance','rotor_torque','turbine_status','cloud_level','blade_length','blade_breadth','windmill_height']])
train_data[['windmill_generated_power']] = sc.fit_transform(train_data[['windmill_generated_power']])



X,y = train_data[['wind_speed','atmospheric_temperature','shaft_temperature','blades_angle','gearbox_temperature','engine_temperature','motor_torque','generator_temperature','atmospheric_pressure','area_temperature','windmill_body_temperature','wind_direction','resistance','rotor_torque','turbine_status','cloud_level','blade_length','blade_breadth','windmill_height']].values , train_data['windmill_generated_power'].values


/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6619: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense 

model = Sequential()
model.add(Dense(8,input_dim=19,activation='sigmoid'))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='mean_squared_error',optimizer='SGD',metrics=['mean_squared_error'])

model.fit(X_train,y_train,epochs=1000,batch_size=20)


Epoch 1/1000
400/400 [==============================] - 1s 1ms/step - loss: 0.0535 - mean_squared_error: 0.0535
Epoch 2/1000
400/400 [==============================] - 1s 1ms/step - loss: 0.0215 - mean_squared_error: 0.0215
Epoch 3/1000
400/400 [==============================] - 1s 1ms/step - loss: 0.0206 - mean_squared_error: 0.0206
Epoch 4/1000
400/400 [==============================] - 1s 1ms/step - loss: 0.0204 - mean_squared_error: 0.0204
Epoch 5/1000
400/400 [==============================] - 1s 2ms/step - loss: 0.0203 - mean_squared_error: 0.0203
Epoch 6/1000
400/400 [==============================] - 1s 1ms/step - loss: 0.0202 - mean_squared_error: 0.0202
Epoch 7/1000
400/400 [==============================] - 1s 1ms/step - loss: 0.0201 - mean_squared_error: 0.0201
Epoch 8/1000
400/400 [==============================] - 1s 1ms/step - loss: 0.0200 - mean_squared_error: 0.0200
Epoch 9/1000
400/400 [==============================] - 1s 1ms/step - loss: 0.0199 - mean_squared_error:

In [ ]:
pre = model.predict(X_test)
print(pre)
print(y_test)

from sklearn.metrics import mean_squared_error
import numpy as np

print(np.sqrt(mean_squared_error(y_test,pre)))
data = sc.inverse_transform(pre)
print(data)
data1 = sc.inverse_transform(y_test.reshape(-1,1))
print(data1)

[[0.16189337]
 [0.17366594]
 [0.25895852]
 ...
 [0.19148895]
 [0.38256496]
 [0.19782698]]
[0.2596934  0.09667971 0.55060778 ... 0.26056053 0.74932306 0.28350027]
0.1011988527684754
[[4.104568 ]
 [4.3303084]
 [5.965803 ]
 ...
 [4.6720667]
 [8.335971 ]
 [4.793599 ]]
[[ 5.97989485]
 [ 2.85408875]
 [11.55821106]
 ...
 [ 5.9965221 ]
 [15.36859908]
 [ 6.43639428]]


In [ ]:
# Forcasting 

x = []
for i in range(1,20):
    x.append(float(input()))  # Inputs

print(x)
    

from sklearn.preprocessing import MinMaxScaler 
sc = MinMaxScaler()

test_data = pd.DataFrame({'wind_speed':[x[0]],'atmospheric_temperature':[x[1]],'shaft_temperature':[x[2]],
                          'blades_angle':[x[3]],'gearbox_temperature':[x[4]],'engine_temperature':[x[5]],'motor_torque':[x[6]],'generator_temperature':[x[7]],'atmospheric_pressure':[x[8]],'area_temperature':[x[9]],
                          'windmill_body_temperature':[x[10]],'wind_direction':[x[11]],'resistance':[x[12]],'rotor_torque':[x[13]],'turbine_status':[x[14]],'cloud_level':[x[15]],
                          'blade_length':[x[16]],'blade_breadth':[x[17]],'windmill_height':[x[18]]})
print(test_data)
test_data[['wind_speed','atmospheric_temperature','shaft_temperature','blades_angle','gearbox_temperature','engine_temperature','motor_torque','generator_temperature','atmospheric_pressure','area_temperature','windmill_body_temperature','wind_direction','resistance','rotor_torque','turbine_status','cloud_level','blade_length','blade_breadth','windmill_height']] = sc.fit_transform(test_data[['wind_speed','atmospheric_temperature','shaft_temperature','blades_angle','gearbox_temperature','engine_temperature','motor_torque','generator_temperature','atmospheric_pressure','area_temperature','windmill_body_temperature','wind_direction','resistance','rotor_torque','turbine_status','cloud_level','blade_length','blade_breadth','windmill_height']])
#
X = test_data[['wind_speed','atmospheric_temperature','shaft_temperature','blades_angle','gearbox_temperature','engine_temperature','motor_torque','generator_temperature','atmospheric_pressure','area_temperature','windmill_body_temperature','wind_direction','resistance','rotor_torque','turbine_status','cloud_level','blade_length','blade_breadth','windmill_height']].values
print(X)
prediction = model.predict(X)
print(prediction)

94.8200
41.723
-0.9034
82.41
42.52
2563.12
76.66
103402.96
26.89
98.98
239.83
2730.31
42.08
0
1.0
2.21
0.31
24.28
78.90
[94.82, 41.723, -0.9034, 82.41, 42.52, 2563.12, 76.66, 103402.96, 26.89, 98.98, 239.83, 2730.31, 42.08, 0.0, 1.0, 2.21, 0.31, 24.28, 78.9]
   wind_speed  atmospheric_temperature  shaft_temperature  blades_angle  \
0       94.82                   41.723            -0.9034         82.41   

   gearbox_temperature  engine_temperature  motor_torque  \
0                42.52             2563.12         76.66   

   generator_temperature  atmospheric_pressure  area_temperature  \
0              103402.96                 26.89             98.98   

   windmill_body_temperature  wind_direction  resistance  rotor_torque  \
0                     239.83         2730.31       42.08           0.0   

   turbine_status  cloud_level  blade_length  blade_breadth  windmill_height  
0             1.0         2.21          0.31          24.28             78.9  
[[0. 0. 0. 0. 0. 0. 0. 0.